### ISSUE TITLE
how to create one project with cli executables

### ISSUE THREAD

**Issue by wey-gu** [pdm-project/pdm-example-monorepo#2]
I didn't see such entry_point defined in pep517, should I go with setup.cfg?

scripts of pdm could only be triggered with `pdm run`, right?

Could we have such examples?(maybe this is the wrong place as it's for multiple models in mono repo, sorry I came to know this after shooting the issue)

**Comment by frostming** [comment]
Short answer from mobile: read PEP 621 and look for project.scripts.

you can also find a real world example from the pdm repo

**Comment by wey-gu** [comment]
Thanks @frostming !!!

I came to reply with this, too(by checking other projects) to see you already pointed to the PEP!

```toml
[project.scripts]
nebulagraph = "nebulagraph_lite.cli:main"
```
